-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Gold SCD2 dimension audiology.dim_appointment (contract incl. SCD2 system columns, CLAUDE §29)
CREATE TABLE [audiology].[dim_appointment] (
    [appointment_id] bigint,
    [patient_id] bigint,
    [clinic_id] int,
    [clinic_name] nvarchar(100),
    [appointment_ts] datetime2(3),
    [appointment_status] nvarchar(30),
    [duration_minutes] int,
    [hash_key] nvarchar(64),
    [effective_from] datetime2(3),
    [effective_to] datetime2(3) NULL,
    [is_current] bit,
    [mrg_ind] varchar(2),
    [created_at] datetime2(3),
    [updated_at] datetime2(3)
);
