-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Bronze landed table audiology.appointment (raw contract; Spark-created managed Delta)
CREATE TABLE [audiology].[appointment] (
    [appointment_id] bigint,
    [patient_id] bigint,
    [clinic_id] int,
    [appointment_ts] datetime2(3),
    [appointment_status] nvarchar(30),
    [duration_minutes] int,
    [modified_at] datetime2(3)
);
