-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Bronze landed table audiology.clinic (raw contract; Spark-created managed Delta)
CREATE TABLE [audiology].[clinic] (
    [clinic_id] int,
    [clinic_name] nvarchar(100),
    [region] nvarchar(50),
    [modified_at] datetime2(3)
);
