-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Gold SCD2 dimension dynamics.dim_contact (contract incl. SCD2 system columns, CLAUDE §29)
CREATE TABLE [dynamics].[dim_contact] (
    [contactid] nvarchar(4000),
    [full_name] nvarchar(4000),
    [email] nvarchar(4000),
    [phone] nvarchar(4000),
    [birth_date] date,
    [postcode] nvarchar(4000),
    [gender_code] int,
    [hash_key] nvarchar(64),
    [effective_from] datetime2(3),
    [effective_to] datetime2(3) NULL,
    [is_current] bit,
    [mrg_ind] varchar(2),
    [created_at] datetime2(3),
    [updated_at] datetime2(3)
);
