-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Bronze landed table dynamics.contact (raw contract; Spark-created managed Delta)
CREATE TABLE [dynamics].[contact] (
    [contactid] nvarchar(4000),
    [firstname] nvarchar(4000),
    [lastname] nvarchar(4000),
    [fullname] nvarchar(4000),
    [emailaddress1] nvarchar(4000),
    [telephone1] nvarchar(4000),
    [mobilephone] nvarchar(4000),
    [birthdate] date,
    [address1_postalcode] nvarchar(4000),
    [gendercode] int,
    [modifiedon] datetime2(3)
);
