table dim_appointment
	lineageTag: 11111111-1111-1111-1111-111111111111

	measure Appointments = COUNTROWS(dim_appointment)
		formatString: #,0
		lineageTag: 1a111111-1111-1111-1111-111111111111

	measure 'Avg Duration (min)' = AVERAGE(dim_appointment[duration_minutes])
		formatString: #,0.0
		lineageTag: 1b111111-1111-1111-1111-111111111111

	column appointment_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: appointment_id
		lineageTag: 1c111111-1111-1111-1111-111111111111

	column clinic_id
		dataType: int64
		summarizeBy: none
		sourceColumn: clinic_id
		lineageTag: 1d111111-1111-1111-1111-111111111111

	column duration_minutes
		dataType: int64
		summarizeBy: sum
		sourceColumn: duration_minutes
		lineageTag: 1e111111-1111-1111-1111-111111111111

	/// PHI pseudonymised at Gold by the framework mask - the model never sees raw PHI. Hidden from report authors.
	column patient_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: patient_id
		lineageTag: 1f111111-1111-1111-1111-111111111111

	column appointment_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: appointment_date
		lineageTag: 10111111-1111-1111-1111-111111111111

	partition dim_appointment = entity
		mode: directLake
		source
			entityName: dim_appointment
			schemaName: audiology
			expressionSource: DatabaseQuery
