-- GENERATED by gen_ddl.py from manifest.yml (the table CONTRACT) - do not hand-edit; edit the manifest + re-run.
-- Bronze landed table audiology.device_telemetry (raw contract; Spark-created managed Delta)
CREATE TABLE [audiology].[device_telemetry] (
    [device_id] nvarchar(4000),
    [patient_ref] bigint,
    [reading_ts] datetime2(3),
    [reading_db] decimal(5,1)
);
